# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------
 
name = "jam"
email = "jamis404@163.com"
link = "https://github.com/jamloveu"
